version: "3"
    
services:
  db:
    image: mysql
    volumes:
      - wallet_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pwxdaiwallet
      MYSQL_DATABASE: xdaiwallet
      MYSQL_USER: xdaiwallet
      MYSQL_PASSWORD: xdaiwallet
    networks:
      - walletwatch
  walletwatch:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: walletwatch
    restart: always
    ports: 
      - 8000:8000
    container_name: walletwatch
    environment:
      - SECRET_KEY=SECRET_KEY_HERE
      - DEBUG=False
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=walletwatch
      - DB_PASSWORD=walletwatch
      - DB_DATABASE=walletwatch
      - TIMEZONE=CET
    depends_on:
      - db
    networks:
      - walletwatch
volumes:
  wallet_data: {}
networks:
  walletwatch : {}